export enum QUERY_KEY {
  GET_EVENT_DETAIL = "GET_EVENT_DETAIL",
  GET_EVENT_LIST = "GET_EVENT_LIST",
  GET_USER_INFO = "GET_USER_INFO",
  GET_JOINED_USER_EVENT_LIST = "GET_JOINED_USER_EVENT_LIST",
  GET_CHECK_JOINED_EVENT = "GET_CHECK_JOINED_EVENT",
}
