export enum ROUTER {
  HOME = "/",
  SIGN_IN = "/sign-in",
  SIGN_UP = "/sign-up",
  FORGET_PASSWORD = "/forget-password",
  PROFILE = "/profile",
  EDIT_PROFILE = "/edit-profile",
  VERIFICATION = "/verification",
  RESET_PASSWORD = "/reset-password",
  CHANGE_PASSWORD = "/change-password",
  MESSAGE = "/messages",
  CALENDAR = "/calendar",
  BOOKMARK = "/bookmark",
  CONTACT_US = "/contact-us",
  SETTINGS = "/settings",
  HELPS_FAQS = "/helps-and-faqs",
  EVENT = "/event",
}
